# Application Configuration
baseUrl=https://uat.apps.uhm.com/customer?iss=https%3A%2F%2Flogin.uat.apps.uhm.com%2F
timeout=30
browser=chrome
#browser=edge
# Set to true to run tests in headless mode
headless=false
# options: maximize, minimize, custom
windowBehavior=maximize
testEmail=tech.ajaythakur@gmail.com

# Test Data
valid_username=qaappstarted@yopmail.com
valid_password=Ajay@8010505397
invalid_username=invalid@uhmcom	
invalid_password=WrongPassword123

#Email Configuration
smtp_host=smtp.gmail.com
smtp_port=587
smtp_user=qa.ajay.thakur@gmail.com
smtp_password=quuoggfrxqsixibv
email_to=tech.ajaythakur@gmail.com

# OTP Configuration
use_otp_override=false
otp_override=123456
test_email=qaappstarted@yopmail.com
yopmail_url=http://www.yopmail.com/en/
otp_retry_count=6
otp_retry_delay_seconds=5

# Home Page
home_page_title=Dashboard
home_page_url=/dashboard